### ISSUE TITLE
Error in main process

### ISSUE THREAD

**Issue by nblackburn** [quanglam2807/singlebox#107]
![image](https://user-images.githubusercontent.com/2931085/72053511-1b840280-32bf-11ea-8996-c595564b1aea.png)

Happening as of `2.5.0` on Windows 10 Pro

**Comment by nblackburn** [comment]
I think it fails because the description is a required field and is not passed when clearing the overlay icon.

https://github.com/quanglam2807/singlebox/blob/master/public/libs/views.js#L300

**Comment by quanglam2807** [comment]
@nblackburn Thanks a lot!!! I'll release the update soon.

**Comment by nblackburn** [comment]
@quanglam2807 No problem, i fixed it myself but you beat me by mere moments in issuing the PR 🥇. Looking forward to the release and the error is driving me insane.

**Comment by quanglam2807** [comment]
@nblackburn haha, I should have slowed down. I'm desperate for PR from other people.
