### ISSUE TITLE
WhatsApp console error

### ISSUE THREAD

**Issue by floq-design** [quanglam2807/singlebox#17]
Hi

Just updated to v1.3.1 and now WhatsApp doesn't run - show Update Google Chrome panel.
Dev tools shows JS error:

`VM85 init.js:166 Unable to load preload script: /Applications/Singlebox.app/Contents/Resources/app.asar/build/preload/view.js`

If I remove service and re-add works until restart Singlebox.

**Comment by quanglam2807** [comment]
Thanks a lot for reporting! This is actually 2 different bugs!! I'll fix both of them ASAP.
