### ISSUE TITLE
bug: Todoist doesn't remain logged in after app startup

### ISSUE THREAD

**Issue by vlad-cotfas** [quanglam2807/singlebox#187]
# Bug Report
**Current Behavior:**

Todoist does not keep the login after app restart.

**Expected Behavior:**

**Steps to Reproduce:**

**Additional Context**

**Comment by vlad-cotfas** [comment]
Any news about this?

**Comment by quanglam2807** [comment]
Thanks for reporting! I'll correct it in the catalog. Still, the app won't be able to update your workspace automatically. To fix this bug, edit workspace and change URL to `https://todoist.com/app`.
