### ISSUE TITLE
feature: More gray out when tab hibernate

### ISSUE THREAD

**Issue by vlad-cotfas** [quanglam2807/singlebox#191]
Mac OS 10.15.4
Singlebox 3.1.0

When the tab is in hibernating state would be nice if the tab is more gray out.

**Comment by vlad-cotfas** [comment]
I saw it was implemented in v3.4.0

I was thinking to make it configurable per workspace :-?

**Comment by quanglam2807** [comment]
> I saw it was implemented in v3.4.0
> 
> 
> 
> I was thinking to make it configurable per workspace :-?

Thanks for suggestion. Personally, I think it’s better not to add an option to change this behavior. If the app is grayed out because it’s hibernated and then you change the option to make it not grayed out, then you would confuse yourself I guess? Still, if you mean something else, feel free to let me know.

**Comment by vlad-cotfas** [comment]
You are right, I did not tought about that, maybe an option in settings to enable/disable the hole thing? 💯

**Comment by quanglam2807** [comment]
@cotfas You don't like the change?

**Comment by vlad-cotfas** [comment]
> @cotfas You don't like the change?

Yes, I like. :)

**Comment by quanglam2807** [comment]
Haha. I asked because if you like the change, why would you need an option to switch it off?

**Comment by vlad-cotfas** [comment]
I was thinking to be configurable for other users who do not need it. :D Also the gray out I think is a little bit to gray out.

**Comment by quanglam2807** [comment]
Thank you for the point! For now, I’d leave it this way as I think it’s not bad to have a way to tell the difference between hibernated and active workspaces. If more users ask for an option to turn it off, I will add it :)
