### ISSUE TITLE
bug: This site can't be reached

### ISSUE THREAD

**Issue by osmanzeki** [quanglam2807/singlebox#230]
# Bug Report
**Current Behavior:**
Once in a while, when I come back to Singlebox, some of my apps seem to have stalled and a message about the site not being reachable is displayed.

**Expected Behavior:**
If no issues with my internet connexion is present, this message should probably not show.

**Steps to Reproduce:**
Hard to reproduce, it just seems to happen after a while. I've seen this on both Windows and OSX.

If there is something I can do to diagnose this issue for you, let me know.

**Additional Context**
```
OS:
macOS

Version:
10.14.6

Processor:
2.5 GHz Intel Core i7

RAM:
16 GB 1600 MHz DDR3

Graphics:
NVIDIA GeForce GT 750M 2 GB
Intel Iris Pro 1536 MB
```

**Comment by quanglam2807** [comment]
Thanks for reporting this. I'm not sure what happened so it'll take some time before this is completely fixed. First, I'll make UI changes to display clearer error message.

**Comment by quanglam2807** [comment]
Resolved with #277.

**Comment by osmanzeki** [comment]
Thank you, will test this and report back on the next release then.

**Comment by quanglam2807** [comment]
Thank you! Here is the beta release: https://github.com/atomery/singlebox/releases/tag/v3.8.0-beta
