### ISSUE TITLE
bug: Unread Count for Gmail displays the wrong value

### ISSUE THREAD

**Issue by osmanzeki** [quanglam2807/singlebox#231]
# Bug Report
**Current Behavior:**
It seems like the unread count for my Gmail app does not indicate the correct value found in Gmail itself.

<img width="249" alt="Screen Shot 2020-05-09 at 10 13 24 AM" src="https://user-images.githubusercontent.com/960438/81476151-39666300-91de-11ea-9fc4-ca8e51a61be1.png">

**Expected Behavior:**
The unread count should sync with the application's count.

**Steps to Reproduce:**
I have seen this in both Windows and OSX. Not sure if this is systematic or a result of a specific set of behaviors and settings in the app.

**Additional Context**
```
OS:
macOS

Version:
10.14.6

Processor:
2.5 GHz Intel Core i7

RAM:
16 GB 1600 MHz DDR3

Graphics:
NVIDIA GeForce GT 750M 2 GB
Intel Iris Pro 1536 MB
```

**Comment by osmanzeki** [comment]
Strangely enough, in the OSX toolbar area, the unread count is correct:
![image](https://user-images.githubusercontent.com/960438/81476198-89ddc080-91de-11ea-9ba2-4ee8a46048d9.png)

**Comment by osmanzeki** [comment]
Looking at the [code](https://github.com/atomery/singlebox/blob/bfd27caff683fe98f9980da144212cc305a1c1f2/public/libs/views.js#L436) for this, it seems like the unread count is basing itself on the title of the website changing to get the unread count.

The current title on my end is:
<img width="323" alt="Screen Shot 2020-05-09 at 10 21 46 AM" src="https://user-images.githubusercontent.com/960438/81476296-43d52c80-91df-11ea-9da2-c10c7383324d.png">

**Comment by osmanzeki** [comment]
I did a quick test to see if the regexp was the issue, but it seems like its working normally:

https://codepen.io/ozeki/pen/KKdRdrO?editors=1111

I'm not sure what is causing this issue to be honest.

**Comment by osmanzeki** [comment]
Could it be possible that we are incrementing the value instead of assigning it?

As shown here:
https://github.com/atomery/singlebox/blob/bfd27caff683fe98f9980da144212cc305a1c1f2/public/libs/views.js#L449

**Comment by osmanzeki** [comment]
One more detail, if I send myself a few emails to get over the 9 notifications case, the icon does appear to update to show the `*`.

![image](https://user-images.githubusercontent.com/960438/81477186-6584e280-91e4-11ea-80b1-87da81a868d3.png)

**Comment by quanglam2807** [comment]
> One more detail, if I send myself a few emails to get over the 9 notifications case, the icon does appear to update to show the `*`.
> 
> ![image](https://user-images.githubusercontent.com/960438/81477186-6584e280-91e4-11ea-80b1-87da81a868d3.png)

Thanks for bringing attention to this. I'm working on it.

**Comment by quanglam2807** [comment]
For the bug, thank you for reporting and doing all the investigations! It's strange as I couldn't find what was wrong in the logic either.

**Comment by osmanzeki** [comment]
Thank you, let me know if I can help in any way.

**Comment by quanglam2807** [comment]
I think I found what causes the bug. The workspaces are stored objects. These objects are kept in the main process, the renderer process and as a JSON. Every time the app is loaded, the JSON is used to populate the main & renderer process. 

When the badge count is changed, to reflect the change, normally, the workspace object will be updated in all three places. But because badge count is retrieved from page title, I decided to have the badge count variable only updated in the renderer. Later, I assume main & renderer process data are consistent so when you rearrange workspaces for example, the renderer data would then be used to overwrite the main process data and write to disk. So the number is accidentally saved to disk and reused incorrectly later. BOOM! BUG!

Can you open `~/Library/Application Support/Singlebox/Settings` (JSON file) and check if any object in `workspaces` has `badgeCount` in it. The structure would look something like this
```json
"workspaces": {
        "14": {
            "107aedb0-8ee8-11ea-b32c-2f9257fd9654": {
                "active": false,
                "hibernated": false,
                "homeUrl": "https://color.adobe.com",
                "id": "107aedb0-8ee8-11ea-b32c-2f9257fd9654",
                "name": "Adobe Color",
                "order": 1,
                "pictureId": "107d5eb0-8ee8-11ea-b32c-2f9257fd9654",
                "picturePath": "/Users/quanglam2807/Library/Application Support/Singlebox/pictures/107d5eb0-8ee8-11ea-b32c-2f9257fd9654.png",
                "lastUrl": "https://color.adobe.com/create"
            },
            "8b3c4080-8ee8-11ea-9739-dde0de5a0733": {
                "active": true,
                "hibernated": false,
                "homeUrl": "https://dartpad.dartlang.org/",
                "id": "8b3c4080-8ee8-11ea-9739-dde0de5a0733",
                "name": "DartPad",
                "order": 2,
                "pictureId": "8b3dee30-8ee8-11ea-9739-dde0de5a0733",
                "picturePath": "/Users/quanglam2807/Library/Application Support/Singlebox/pictures/8b3dee30-8ee8-11ea-9739-dde0de5a0733.png",
                "lastUrl": "https://dartpad.dartlang.org/"
            }
        }
    },
```

**Comment by osmanzeki** [comment]
> I think I found what causes the bug. The workspaces are stored objects. These objects are kept in the main process, the renderer process and as a JSON. Every time the app is loaded, the JSON is used to populate the main & renderer process.
> 
> When the badge count is changed, to reflect the change, normally, the workspace object will be updated in all three places. But because badge count is retrieved from page title, I decided to have the badge count variable only updated in the renderer. Later, I assume main & renderer process data are consistent so when you rearrange workspaces for example, the renderer data would then be used to overwrite the main process data and write to disk. So the number is accidentally saved to disk and reused incorrectly later. BOOM! BUG!
> 
> Can you open `~/Library/Application Support/Singlebox/Settings` (JSON file) and check if any object in `workspaces` has `badgeCount` in it. The structure would look something like this
> 
> ```json
> "workspaces": {
>         "14": {
>             "107aedb0-8ee8-11ea-b32c-2f9257fd9654": {
>                 "active": false,
>                 "hibernated": false,
>                 "homeUrl": "https://color.adobe.com",
>                 "id": "107aedb0-8ee8-11ea-b32c-2f9257fd9654",
>                 "name": "Adobe Color",
>                 "order": 1,
>                 "pictureId": "107d5eb0-8ee8-11ea-b32c-2f9257fd9654",
>                 "picturePath": "/Users/quanglam2807/Library/Application Support/Singlebox/pictures/107d5eb0-8ee8-11ea-b32c-2f9257fd9654.png",
>                 "lastUrl": "https://color.adobe.com/create"
>             },
>             "8b3c4080-8ee8-11ea-9739-dde0de5a0733": {
>                 "active": true,
>                 "hibernated": false,
>                 "homeUrl": "https://dartpad.dartlang.org/",
>                 "id": "8b3c4080-8ee8-11ea-9739-dde0de5a0733",
>                 "name": "DartPad",
>                 "order": 2,
>                 "pictureId": "8b3dee30-8ee8-11ea-9739-dde0de5a0733",
>                 "picturePath": "/Users/quanglam2807/Library/Application Support/Singlebox/pictures/8b3dee30-8ee8-11ea-9739-dde0de5a0733.png",
>                 "lastUrl": "https://dartpad.dartlang.org/"
>             }
>         }
>     },
> ```

I see! Indeed, all my workspaces have that value actually.

![image](https://user-images.githubusercontent.com/960438/81479818-b819cb00-91f3-11ea-916f-7277d9981abe.png)

**Comment by osmanzeki** [comment]
I deleted the badgeCount key + value from each workspace, saved the JSON and restarted Singlebox and I can confirm that this seems to have fixed the bug. I definitely did reorder my workspaces a few times so I can confirm that your lead is good as to the reason why this occured.

Do you think this will need a patch in order to both fix the issue and remove the key if it exists in the workspace json?

**Comment by quanglam2807** [comment]
@osmanzeki Thank you for testing and the suggestions. I just pushed the fix (#234). I'm not sure if the way I fixed it is good practice but I simply strip `badgeCount` when saving to JSON and ignore `badgeCount` when loading from JSON.

**Comment by osmanzeki** [comment]
That seems like the best possible fix in my opinion as well. Thank you! :)

**Comment by quanglam2807** [comment]
Thank you! It's temporary fix.  I'll migrate `badgeCount` somewhere else later.
