### ISSUE TITLE
feature: Add option to hide shortcut help tip

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/singlebox#304]
> Hello! I am wondering if there's any way to hide the left sidebar shortcuts helptip, the "Cmd + 1", "Cmd + 2", ... indications below each of the icons on the left i was looking via custom CSS injection but im not sure if i can tweak the canvas of the whole app Thanks! Josep

**Comment by vlad-cotfas** [comment]
I would like it as configurable.

**Comment by quanglam2807** [comment]
Resolved with https://github.com/atomery/singlebox/pull/305
