### ISSUE TITLE
feature: Add a "Mute all" button

### ISSUE THREAD

**Issue by martifenosa** [quanglam2807/singlebox#42]
# Feature Request
Add an on/off button to toggle all notifications. 

**Additional Context**
When working sometimes it's useful being able to mute all distractions. Franz had this feature and for now it's the only thing I'm missing.

**Comment by quanglam2807** [comment]
Thanks for the suggestion! I'm working on it now.

**Comment by quanglam2807** [comment]
@martifenosa  @hacknug I've finished it! Can you give it a try https://send.firefox.com/download/9bb5c69930da3aa6/#pVzJiBS1IrJ4tVm8Cy2Y-A before I release it?

**Comment by quanglam2807** [comment]
Official build: https://github.com/quanglam2807/singlebox/releases/download/v1.7.0/Singlebox-1.7.0.dmg

**Comment by martifenosa** [comment]
@quanglam2807 It's perfect! Thank's!

**Comment by martifenosa** [comment]
@quanglam2807 I don't know if the last update broke this but it's not working now. 
I've got it muted and it still does the whatsapp sound whenever I receive a message :P

I believe it was working flawless before.

**Comment by quanglam2807** [comment]
@martifenosa at the moment, when you turn off notifications, the app only turns off [HTML5 notifications](https://developer.mozilla.org/en/docs/Web/API/notification), not including the audio. I'll try to make a fix for this soon.

**Comment by martifenosa** [comment]
Great! Ty

**Comment by hacknug** [comment]
You have a typo: `Unitl tommorrow` should be `Until tomorrow`. Everything else seems to work fine (besides the audio not being muted, of course).

My only issue with the current implementation is that we either mute all the apps or none. Would love to be able to mute per app/workspace. Right click on the icon shows an option to toggle notifications and or sound. Being able to disable workspaces would also be great. I can open a separate issue for all of these if you want.

**Comment by quanglam2807** [comment]
@hacknug Thanks a lot! And yes, it'd be great if you can create new issues for those feature requests. I'd probably leave those features to the end of December as I want to make sure all the new features are stable first.
