### ISSUE TITLE
app: Spotify

### ISSUE THREAD

**Issue by hacknug** [quanglam2807/singlebox#45]
# App Submission

- **Name:** Spotify
- **URL:** https://open.spotify.com/
- **Category:** Music
- **Icon:** https://developer.spotify.com/branding-guidelines/

**Comment by quanglam2807** [comment]
I'm sorry but because Spotify uses proprietary DRM technology, it's not supported by Singlebox. FWI, check the Criticism section: https://en.wikipedia.org/wiki/Widevine
