### ISSUE TITLE
app: Figma

### ISSUE THREAD

**Issue by hacknug** [quanglam2807/singlebox#65]
# App Submission

- **Name:** Figma
- **URL:** https://www.figma.com/
- **Category:** Graphics & Design
- **Icon:** Couldn't find a brand assets page on their site.

**Comment by quanglam2807** [comment]
Thanks for the submission! I don't remember exactly but I think I removed Figma from the catalog because of compatibility issues. Would you mind creating custom workspace for Figma to see if it works correctly?

**Comment by hacknug** [comment]
Seems to work fine, even when exporting a zip of icons. Thank you ❤️

**Comment by quanglam2807** [comment]
That's great! Thank you for letting me know.
