### ISSUE TITLE
bug: Google prevents signing in because of security concerns

### ISSUE THREAD

**Issue by quanglam2807** [quanglam2807/singlebox#77]
# Bug Report
**Current Behavior:**

<img width="552" alt="Screen Shot 2019-12-09 at 3 44 09 PM" src="https://user-images.githubusercontent.com/1548835/70475830-07b86700-1a9b-11ea-86fd-13ad4a130529.png">

**Expected Behavior:**

Should be able to sign in with Google

**Steps to Reproduce:**

**Additional Context**

Related to https://github.com/quanglam2807/webcatalog/issues/455

**Comment by quanglam2807** [comment]
This bug is quite critical. Does anyone have the same issue?

**Comment by martifenosa** [comment]
It's working fine for me. I have two google accounts gmails up and running.

**Comment by quanglam2807** [comment]
Thanks for reporting, @martifenosa!

But things are escalating quickly:
https://news.ycombinator.com/item?id=21765615
https://www.reddit.com/r/kde/comments/e7136e/google_bans_falkon_and_konqueror_browsers/
