### ISSUE TITLE
bug: When reordering the different workspaces an error popup appears

### ISSUE THREAD

**Issue by martifenosa** [quanglam2807/singlebox#80]
# Bug Report
**Current Behavior:**
When reordering the different workspaces an error popup shows up. The task is completed successfully though. 

**Steps to Reproduce:**
Just drag one workspace to take the place of another. 

**Additional Context**
<img width="480" alt="Screenshot 2019-12-11 at 17 15 53" src="https://user-images.githubusercontent.com/12196520/70639079-3b7dc300-1c3a-11ea-92f8-e1658a8c27d0.png">

Hope it helps! Keep going

**Comment by quanglam2807** [comment]
Thanks for reporting! It's fixed by #79.
