### ISSUE TITLE
bug: Broken workspaces with v2.2.0

### ISSUE THREAD

**Issue by hacknug** [quanglam2807/singlebox#89]
# Bug Report
**Current Behavior:**
At least WhatsApp and Discord are broken due to #88. Trello also shows a message saying it's not compatible with such version of Edge.

**Expected Behavior:**
Everything would work as before. Of course this would mean Google wouldn't prevent from signin in on places where you could need it.

**Steps to Reproduce:**
Use v2.2.0 and check WhatsApp, Discord and/or Trello. There might be other workspaces affected by this.

**Additional Context**
https://github.com/quanglam2807/singlebox/blob/2f1c48909d59b7cdadf7e581bc2c4d1bf69ffef2/public/libs/views.js#L193-L194

**Comment by hacknug** [comment]
@quanglam2807 Discord and Trello are working fine but WhatsApp is now showing the Google Chrom 49+ screen and flashing (guess it's because it might be reloading)

**Comment by quanglam2807** [comment]
@hacknug Thanks for letting me know. I'm actually working on a fix. All those apps use non-standard user-agent sniffing techniques so they cause all kinds of trouble.
